version: "3.8"
services:
  api:
    build: ./src/api
    ports:
      - 5187:80
      - 4200:4200
      - 4300:4300
      - 5432:5432
  frontend:
    build: ./src/frontend
    ports:
      - 3000:3000
    depends_on:
      - api