version: "3.8"
services:
  database:
    image: crate
    ports:
      - 4200:4200
      - 4300:4300
      - 5432:5432
  schema:
    build: ./src/schema
    ports:
      - 4000:4000
  frontend:
    build: ./src/frontend
    ports:
      - 3000:3000
    depends_on:
      - schema