import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <html lang='en'>
    <head>
      <title>Component Catalog</title>
    </head>
    <body className={inter.className}>
      <header className='bg-green-50 font-extrabold text-lg'>
        <nav className='flex flex-row gap-4 px-8 py-4'>
          <Link href='/'>Main</Link>
          <Link href='/components'>Components</Link>
        </nav>
        <hr />
      </header>
      {children}
    </body>
  </html>
}
